# add extra message for error
# yes no
DEBUG = yes

# kinda like gdb, add commands like breakpoints, print registers and value in memory ...
# yes no
STEP = yes

# enable some optimisation, does not behave like a real gameboy would for some rom
# yes no
FAST = no

# enable profiling option
# yes no
PROFILING = no

##### DO NOT TOUCH BELOW THIS #####

C_FLAGS = -std=c2x -Wall -DREALITY
LD_FLAGS_ADDITIONAL =
STRIP = yes

#setup profiling
ifeq ($(PROFILING), yes)
	C_FLAGS += -pg
    LD_FLAGS_ADDITIONAL += -pg
    STRIP = no

    # if profiling, setup debug
    ifeq ($(DEBUG),yes)
        C_FLAGS += -DDEBUG
    else ifeq ($(DEBUG),no)
    else
        $(error DEBUG is not correctly set (yes/no))
    endif

else ifeq ($(PROFILING), no)
    # if no profiling, setup debug
    ifeq ($(DEBUG),yes)
        C_FLAGS += -g -DDEBUG
        LD_FLAGS_ADDITIONAL += -g
        STRIP = no
    else ifeq ($(DEBUG),no)
        C_FLAGS += -O3
    else
        $(error DEBUG is not correctly set (yes/no))
    endif
else
    $(error PROFILING is not correctly set (yes/no))
endif

ifeq ($(STEP), yes)
	C_FLAGS += -DSTEP
else ifeq ($(STEP), no)
else
    $(error STEP is not correctly set (yes/no))
endif

ifeq ($(FAST), yes)
	C_FLAGS += -DFAST
else ifeq ($(FAST), no)
else
    $(error FAST is not correctly set (yes/no))
endif